### ISSUE TITLE
Courses contaning non ASCII chars results in 404

### ISSUE THREAD

**Issue by fredrir** [runarsae/karakterer-net#145]
Probaly due to not properly decoding and encoding the code in  /courses/[CODE] 

E.g TIØ4155: 
![image](https://github.com/user-attachments/assets/59371f73-01bc-471e-8a50-bcbc80e127e4)

or: SØK8514:
![image](https://github.com/user-attachments/assets/50cd60f4-a1b2-4cd9-aeea-36f2e11e5ed0)

**Comment by runarsae** [comment]
Good catch! Thanks for pointing it out.
